Change alacritty checking in bspwm startup file to st checking; Update submodule .config/nvim

diff --git a/.config/bspwm/bspwmrc b/.config/bspwm/bspwmrc
--- a/.config/bspwm/bspwmrc
+++ b/.config/bspwm/bspwmrc
@@ -14,10 +14,10 @@ else
     fi
 fi
 
-command -v alacritty >/dev/null 2>&1
+command -v st >/dev/null 2>&1
 return_val=$?
 if [ $return_val -ne 0 ]; then
-    echo >&2 "Can't seem to find the alacritty executable. Exiting!"
+    echo >&2 "Can't seem to find the st executable. Exiting!"
     bspc quit && exit 1
 fi
 
